GET http://localhost:8000/api/v1/hotels HTTP/1.1

###

GET http://localhost:8000/api/v1/hotels/679b61b61153db8029745c94 HTTP/1.1

###

DELETE http://localhost:8000/api/v1/hotels/679b61cc1153db8029745c9a

###

POST http://localhost:8000/api/v1/hotels HTTP/1.1
content-type: application/json

{
    "name": "Hotel 067",
    "address": "...",
    "room_price": 307,
    "comfort": "4",
    "summary": "...",
    "image_cover": "https://dummyimage.com/320x240/999/ddd.jpg&text=[placeholder]"
}

###

POST http://localhost:8000/api/v1/hotels HTTP/1.1
content-type: application/json
Authorization: token: ...

{
    "name": "Hotel 068",
    "address": "...",
    "room_price": 308,
    "comfort": "4",
    "summary": "...",
    "image_cover": "https://dummyimage.com/320x240/999/ddd.jpg&text=[placeholder]"
}

###

PATCH http://localhost:8000/api/v1/hotels/679b61a51153db8029745c92 HTTP/1.1
content-type: application/json

{
    "room_price": "302",
    "summary": "Description for Hotel 062..."
}

###

POST http://localhost:8000/api/v1/users/signup HTTP/1.1
content-type: application/json

{
    "name": "user1",
    "email": "user1@mail.com",
    "password": "helloworld",
    "passwordConfirm": "helloworld"
}

###

POST http://localhost:8000/api/v1/users/login HTTP/1.1
content-type: application/json

{
    "name": "user1",
    "email": "user1@mail.com",
    "password": "hello?"
}

###

POST http://localhost:8000/api/v1/users/login HTTP/1.1
content-type: application/json

{
    "name": "user1",
    "email": "user1@mail.com",
    "password": "helloworld"
}