GET http://localhost:8000/api/v1/hotels HTTP/1.1

###

GET http://localhost:8000/api/v1/hotels/3 HTTP/1.1

###

POST http://localhost:8000/api/v1/hotels HTTP/1.1
content-type: application/json

{
    "name": "Hotel 061",
    "address": "..."
}
